platform :ios, '9.0'

target 'ToDoListApp' do

  use_frameworks!

  # Pods for ToDoListApp

pod 'RealmSwift'
pod 'SwipeCellKit'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'

end
